# Generated by Django 4.2.7 on 2023-11-30 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CE', 'Tạo đơn'), ('PR', 'Chuẩn bị'), ('DE', 'Đang giao'), ('DR', 'Đã giao'), ('CA', 'Đơn hủy')], default='CE', max_length=2)),
                ('receiver', models.CharField(blank=True, default='', max_length=50, verbose_name='Người nhận')),
                ('address', models.CharField(blank=True, default='', max_length=50, verbose_name='Địa chỉ nhận hàng')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Số điện thoại')),
                ('orderedTime', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian đặt')),
                ('receiveTime', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm nhận')),
                ('total', models.IntegerField(default=0, verbose_name='Tổng đơn')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AD', 'Trong giỏ'), ('CH', 'Chọn đặt'), ('OR', 'Đã đặt'), ('CA', 'Đơn hủy')], default='AD', max_length=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.product')),
            ],
            options={
                'verbose_name_plural': 'Giỏ hàng',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=250, verbose_name='Địa chỉ')),
                ('default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name_plural': 'Địa chỉ',
            },
        ),
    ]
